### ISSUE TITLE
Cannot grant permissions in AWS web ui

### ISSUE THREAD

**Issue by d-lapirov** [bees-hive/aws-creds#2]
After singing in, when I click on the `allow` button (pic below)
![image](https://github.com/bees-hive/aws-creds/assets/97545044/a35803e7-5756-4d28-9dec-486e96398b38)
I get the following error (pic below)
![image](https://github.com/bees-hive/aws-creds/assets/97545044/73f0970d-2338-49e5-8982-ee3665321d72)

What additional info can I provide?

**Comment by extsoft** [comment]
@d-lapirov, the issue is caused by the wrong region being used for the AWS IAM Identity Center. Please double-check the region you use. Maybe you need to re-generate aliases with `aws-creds scan-local`.

P.S. There are some other changes, so, I recommend to install the latest version.

**Comment by d-lapirov** [comment]
You are correct. I did pass incorrect region. Now it's working as expected.
